# Generated by Django 5.2.12 on 2026-03-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_paymentwebhooklog_promotion_shippingmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_otp_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_otp_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
